### ISSUE TITLE
Doesn't work in conjuction with CR HLS Player

### ISSUE THREAD

**Issue by Keepco** [Onestay/CR-Unblocker#10]
Hello,
while this application works great, it sadly doesn't work in conjuction with [CR HLS Player](https://chrome.google.com/webstore/detail/cr-hls-player/aeajdeepnjjdekpbicjhfldagkjndjid), which allows one to view crunchyroll without Flash. Would it be possible to somehow get both working together?
(Feel free to close this issue, if that isn't the case)

**Comment by Onestay** [comment]
My time right now is pretty limited due to school and other projects. If I have some spare time I'll look into it. Can't promise anything tho.

**Comment by Keepco** [comment]
Take your time, I'll just use Chrome in the mean time. Thanks for looking into it :)

**Comment by Onestay** [comment]
I've looked into it and it seems like the HLS Player is doing something with the session id too. These two might conflict in some way. It seems like a lot of work to make them work together so I'll probably not add this. 
Sorry :c

**Comment by Keepco** [comment]
Okay, I'll keep using chrome for CR then and hope that they'll implement a HTML5 player *soon*. Thanks for looking into it

**Comment by LynnAU** [comment]
So I thought I'd just revive this thread momentarily after trying to replace the default Flash player with a HTML5 one with HLS. Basically the player the CR-HLS extension used...

Crunchyroll changed how they're serving the information for the video. And while I can retrieve the video from the API, their subtitles are encrypted and require to be decrypted on the fly. The other problem is the format of the decrypted subtitles, it's Crunchyroll's own format as far as I know and even when converting it to the SRT format. I can't use it on the player since the video player requires a file instead of just a text string for subtitles...
