### ISSUE TITLE
Was working a few days ago, now seems to be broken

### ISSUE THREAD

**Issue by gomera** [Onestay/CR-Unblocker#14]
Every time I tries to go to a show page, there is a popup informing the crash:

<img width="394" alt="screen shot 2017-04-16 at 12 33 24 am" src="https://cloud.githubusercontent.com/assets/1063134/25065663/94301394-223d-11e7-9a10-5ec6019efc8a.png">

Don't know if this helps but this is the outout of the dev console:

<img width="1440" alt="screen shot 2017-04-16 at 12 38 36 am" src="https://cloud.githubusercontent.com/assets/1063134/25065668/a5b2399e-223d-11e7-91c3-4667fab12154.png">

and this is the requests that seems to be failing:

![screen shot 2017-04-16 at 12 39 25 am](https://cloud.githubusercontent.com/assets/1063134/25065674/bf2781b8-223d-11e7-8934-9c9ec2056788.png)

Host info:
macOS Sierra: 10.12.3
Chrome: 56.0.2924.87 (64-bit)

Let me know if you need anything else.

**Comment by Ar1sC** [comment]
Same Error. Windows 10 Chrome Version 57.0.2987.133 (64-bit)

**Comment by Onestay** [comment]
Yes it's a server side problem. Both my server and the backup server can't get an session id. I'm not at home right now and can't look into it. I will try to fix it once I get home.

**Comment by Onestay** [comment]
@rubbixcube could you maybe look into it?

**Comment by Onestay** [comment]
Should be working again now. 
Instead of using the Crunchyroll website to get the sessionId I'm now using the API. It's actually undocumented and I only found this way through here https://github.com/KolbyClark/Crunchyroll-HLS-Player/blob/master/src/bgp.js#L82 .
If you experience any further issues please let me know.

**Comment by lmmfranco** [comment]
Seems to be working as intended now 👍

**Comment by RubbixCube** [comment]
Updated my end as well so the backup server should be all good. Took way longer than I wanted it to have to switch over to the API, and on top of that failing at understanding said API. All is good now...

Also going to make a pull request since I changed the files over to a subdomain, `https://crunchy.rubbix.net/`

**Comment by Onestay** [comment]
I think i can close that issue now.

**Comment by gomera** [comment]
BTW, thanks a lot for the quick fix !

**Comment by gomera** [comment]
BTW, thanks a lot for the quick fix !
