### ISSUE TITLE
Extension causes logout from CR site

### ISSUE THREAD

**Issue by mendhak** [Onestay/CR-Unblocker#20]
Hello, I've been noticing I keep getting logged out from Crunchyroll quite frequently.  I was able to reproduce the problem in these ways:

* close+open the browser (including the Chrome tray)  - there is a slight delay and the tab reloads
* restart the computer
* click the CR-Unblocker extension

I did some tracing, I believe it's down to the `setUsCookie` running when Chrome starts or the site is opened.  This causes the `sess_id` and `c_locale` cookies to be replaced, which in turn causes a logout on the CR site.

Anyone else seeing this issue?

You are more familiar with the systems involved but at a quick glance, a fix for this could be:

* Check if the `c_locale` has already been set, if so, don't replace it
* Set `c_locale` as a non-session cookie so that it doesn't go away on each restart

I'll submit a PR for this based on my understanding, please feel free to accept/reject/delay/rewrite as you please.

**Comment by RubbixCube** [comment]
This is definitely something I've noticed as well. Something that crunchyroll implemented on their side...

I'll also jump in and do some editing of the extension myself and see if I can get anywhere...

**Comment by Onestay** [comment]
I'm currently really busy. If there is anybody wanting to fix that for me that would be great. Sorry I can't maintain it right now

**Comment by Blightwidow** [comment]
We are modifying slightly the way the extension run but here is a quick explenation why it disconnect you and why we cannot do something about it for now.

When you load a crunchyroll page, the script check if the locale is in the US (not by watching the cookie, but by reading an HTML element). If it's not US, the page get a US session ID and reload. The problem is we cannot change the sessionId and keep you logged in without triggering the DDOS protection of crunchyroll. 

For now, everytime your Chrome session end, you loose the cookie we set and you will get another one which will disconnect you.
