### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by cAstraea** [Onestay/CR-Unblocker#26]
Hey, tried to contact you on twitter about a security issue but couldn't get through :-)
 My email is razvan.comsa@live.com

**Comment by RubbixCube** [comment]
Gonna hijack this thread if you don't mind.

We've been notified that a user was accidentally logged into an account that they did own, this is a serious issue since crunchyroll doesn't have any confirmation safe guards before you buy anything on the store/website. So we've rolled back the chrome webstore version to v1.5 which is before we added this feature.

Until we figure out a working solution and we're sure that this won't happen again, we won't republish the version until then.
